"""Add missing indexes

Revision ID: 20f3c3d35d1a
Revises: bba0370605f6
Create Date: 2025-08-23 12:25:25.774591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20f3c3d35d1a'
down_revision = 'bba0370605f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.execute('ALTER TABLE course ADD COLUMN is_renewal BOOLEAN DEFAULT 0')
        batch_op.execute('ALTER TABLE course ADD COLUMN renewal_from_course_id INTEGER REFERENCES course(id)')
        batch_op.execute('ALTER TABLE course ADD COLUMN custom_course_cost FLOAT')
        # 将原来的 cost 字段重命名为 base_cost
        batch_op.execute('ALTER TABLE course ADD COLUMN base_cost FLOAT')
        # 删除原来的 cost 字段
        batch_op.execute('ALTER TABLE course DROP COLUMN cost')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cost', sa.FLOAT(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('course_type',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('customer_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
        batch_op.drop_column('custom_course_cost')
        batch_op.drop_column('renewal_from_course_id')
        batch_op.drop_column('is_renewal')

    # ### end Alembic commands ###
