"""Add assigned_employee_id to Course model

Revision ID: bba0370605f6
Revises: 
Create Date: 2025-08-23 12:20:39.048403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bba0370605f6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.execute('ALTER TABLE course ADD COLUMN assigned_employee_id INTEGER REFERENCES employee(id)')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('customer_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
        batch_op.drop_column('custom_course_cost')
        batch_op.drop_column('renewal_from_course_id')
        batch_op.drop_column('is_renewal')
        batch_op.drop_column('assigned_employee_id')

    # ### end Alembic commands ###
